import type { PromptTag, PromptTagSection } from './promptTags'

type CharacterEntry = readonly [englishName: string, chineseName: string, aliases?: readonly string[]]

function characterTags(id: string, ipName: string, entries: readonly CharacterEntry[]): PromptTag[] {
  return entries.map(([englishName, labelZh, aliases]) => ({
    id: `ip-${id}-${englishName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')}`,
    labelZh,
    prompt: `${englishName} (${ipName})`,
    ...(aliases?.length ? { aliases } : {}),
  }))
}

const genshinImpact = characterTags('genshin', 'genshin impact', [
  ['Jean', '琴'],
  ['Amber', '安柏'],
  ['Lisa', '丽莎'],
  ['Kaeya', '凯亚'],
  ['Barbara', '芭芭拉'],
  ['Diluc', '迪卢克'],
  ['Razor', '雷泽'],
  ['Venti', '温迪'],
  ['Klee', '可莉'],
  ['Bennett', '班尼特'],
  ['Noelle', '诺艾尔'],
  ['Fischl', '菲谢尔'],
  ['Sucrose', '砂糖'],
  ['Mona', '莫娜'],
  ['Diona', '迪奥娜'],
  ['Albedo', '阿贝多'],
  ['Rosaria', '罗莎莉亚'],
  ['Eula', '优菈'],
  ['Mika', '米卡'],
  ['Dahlia', '塔利雅'],
  ['Varka', '法尔伽'],
  ['Lohen', '洛恩'],
  ['Xiao', '魈'],
  ['Beidou', '北斗'],
  ['Ningguang', '凝光'],
  ['Xiangling', '香菱'],
  ['Xingqiu', '行秋'],
  ['Chongyun', '重云'],
  ['Qiqi', '七七'],
  ['Keqing', '刻晴'],
  ['Zhongli', '钟离'],
  ['Xinyan', '辛焱'],
  ['Ganyu', '甘雨'],
  ['Hu Tao', '胡桃'],
  ['Yanfei', '烟绯'],
  ['Shenhe', '申鹤'],
  ['Yun Jin', '云堇'],
  ['Yelan', '夜兰'],
  ['Yaoyao', '瑶瑶'],
  ['Baizhu', '白术'],
  ['Xianyun', '闲云'],
  ['Gaming', '嘉明'],
  ['Lan Yan', '蓝砚'],
  ['Zibai', '兹白'],
  ['Kamisato Ayaka', '神里绫华', ['Ayaka']],
  ['Kaedehara Kazuha', '枫原万叶', ['Kazuha']],
  ['Yoimiya', '宵宫'],
  ['Sayu', '早柚'],
  ['Raiden Shogun', '雷电将军'],
  ['Kujou Sara', '九条裟罗', ['Sara']],
  ['Sangonomiya Kokomi', '珊瑚宫心海', ['Kokomi']],
  ['Thoma', '托马'],
  ['Arataki Itto', '荒泷一斗', ['Itto']],
  ['Gorou', '五郎'],
  ['Yae Miko', '八重神子'],
  ['Kamisato Ayato', '神里绫人', ['Ayato']],
  ['Kuki Shinobu', '久岐忍', ['Shinobu']],
  ['Shikanoin Heizou', '鹿野院平藏', ['Heizou']],
  ['Kirara', '绮良良'],
  ['Yumemizuki Mizuki', '梦见月瑞希', ['Mizuki']],
  ['Tighnari', '提纳里'],
  ['Collei', '柯莱'],
  ['Dori', '多莉'],
  ['Cyno', '赛诺'],
  ['Candace', '坎蒂丝'],
  ['Nilou', '妮露'],
  ['Nahida', '纳西妲'],
  ['Layla', '莱依拉'],
  ['Wanderer', '流浪者', ['散兵', 'Scaramouche']],
  ['Faruzan', '珐露珊'],
  ['Alhaitham', '艾尔海森'],
  ['Dehya', '迪希雅'],
  ['Kaveh', '卡维'],
  ['Sethos', '赛索斯'],
  ['Lyney', '林尼'],
  ['Lynette', '琳妮特'],
  ['Freminet', '菲米尼'],
  ['Neuvillette', '那维莱特'],
  ['Wriothesley', '莱欧斯利'],
  ['Furina', '芙宁娜'],
  ['Charlotte', '夏洛蒂'],
  ['Navia', '娜维娅'],
  ['Chevreuse', '夏沃蕾'],
  ['Chiori', '千织'],
  ['Arlecchino', '阿蕾奇诺', ['仆人', 'The Knave']],
  ['Clorinde', '克洛琳德'],
  ['Sigewinne', '希格雯'],
  ['Emilie', '艾梅莉埃'],
  ['Escoffier', '爱可菲'],
  ['Mualani', '玛拉妮'],
  ['Kachina', '卡齐娜'],
  ['Kinich', '基尼奇'],
  ['Xilonen', '希诺宁'],
  ['Chasca', '恰斯卡'],
  ['Ororon', '欧洛伦'],
  ['Mavuika', '玛薇卡'],
  ['Citlali', '茜特菈莉'],
  ['Iansan', '伊安珊'],
  ['Varesa', '瓦雷莎'],
  ['Ifa', '伊法'],
  ['Ineffa', '伊涅芙'],
  ['Lauma', '菈乌玛'],
  ['Aino', '爱诺'],
  ['Flins', '菲林斯'],
  ['Nefer', '奈芙尔'],
  ['Jahoda', '雅珂达'],
  ['Durin', '杜林'],
  ['Columbina', '哥伦比娅', ['少女', 'The Damselette']],
  ['Illuga', '叶洛亚'],
  ['Linnea', '莉奈娅'],
  ['Nicole', '妮可', ['Nicole Reeyn', '妮可·莱恩']],
  ['Prune', '布伦妮'],
  ['Sandrone', '桑多涅', ['木偶', 'Marionette']],
  ['Tartaglia', '达达利亚', ['公子', 'Childe']],
  ['Odette', '奥黛塔'],
  ['Alyosha', '阿罗夏'],
  ['Aloy', '埃洛伊'],
  ['Skirk', '丝柯克'],
  ['Traveler', '旅行者'],
  ['Aether', '空'],
  ['Lumine', '荧'],
  ['Vesna', '薇斯纳', ['Vesna Strivozha']],
  ['Vodyanitsa', '沃雅妮莎'],
  ['Valeriy', '瓦列里'],
  ['Danica', '达妮卡'],
  ['Noy', '诺伊'],
  ['Mitya', '米提亚'],
  ['Tsaritsa', '冰之女皇', ['安娜丝塔夏·费奥多罗夫娜·雪奈茨娜娅']],
  ['Pulcinella', '普契涅拉', ['公鸡', 'The Rooster']],
  ['Pantalone', '潘塔罗涅', ['富人', 'Regrator']],
  ['Alice', '艾莉丝'],
  ['Dainsleif', '戴因斯雷布'],
])

const honkaiStarRail = characterTags('star-rail', 'Honkai: Star Rail', [
  ['Acheron', '黄泉'],
  ['Aglaea', '阿格莱雅'],
  ['Anaxa', '那刻夏'],
  ['Archer', 'Archer', ['卫宫', 'EMIYA']],
  ['Argenti', '银枝'],
  ['Arlan', '阿兰'],
  ['Ashveil', '不死途'],
  ['Asta', '艾丝妲'],
  ['Aventurine', '砂金'],
  ['Bailu', '白露'],
  ['Black Swan', '黑天鹅'],
  ['Blade', '刃'],
  ['Boothill', '波提欧'],
  ['Bronya', '布洛妮娅'],
  ['Castorice', '遐蝶'],
  ['Cerydra', '刻律德菈'],
  ['Cipher', '赛飞儿'],
  ['Clara', '克拉拉'],
  ['Cyrene', '昔涟'],
  ['Dan Heng', '丹恒'],
  ['Dan Heng • Imbibitor Lunae', '丹恒·饮月', ['饮月', 'Imbibitor Lunae']],
  ['Dan Heng • Permansor Terrae', '丹恒·腾荒', ['腾荒', 'Permansor Terrae']],
  ['Dr. Ratio', '真理医生'],
  ['Evanescia', '绯英'],
  ['Feixiao', '飞霄'],
  ['Firefly', '流萤'],
  ['Fu Xuan', '符玄'],
  ['Gallagher', '加拉赫'],
  ['Gepard', '杰帕德'],
  ['Gilgamesh', '吉尔伽美什'],
  ['Guinaifen', '桂乃芬'],
  ['Hanya', '寒鸦'],
  ['Herta', '黑塔'],
  ['Himeko', '姬子'],
  ['Himeko • Nova', '姬子·启行', ['Himeko Nova']],
  ['Hook', '虎克'],
  ['Huohuo', '藿藿'],
  ['Hyacine', '风堇'],
  ['Hysilens', '海瑟音'],
  ['Jade', '翡翠'],
  ['Jiaoqiu', '椒丘'],
  ['Jing Yuan', '景元'],
  ['Jingliu', '镜流'],
  ['Kafka', '卡芙卡'],
  ['Lingsha', '灵砂'],
  ['Luka', '卢卡'],
  ['Luocha', '罗刹'],
  ['Lynx', '玲可'],
  ['March 7th', '三月七'],
  ['Evernight', '长夜月', ['March 7th • Evernight']],
  ['Misha', '米沙'],
  ['Mortenax Blade', '千冶·刃'],
  ['Moze', '貊泽'],
  ['Mydei', '万敌'],
  ['Natasha', '娜塔莎'],
  ['Pela', '佩拉'],
  ['Phainon', '白厄'],
  ['Qingque', '青雀'],
  ['Rappa', '乱破'],
  ['Rin Tohsaka', '远坂凛'],
  ['Robin', '知更鸟'],
  ['Robin • Summeretto', '知更鸟·晴歌', ['Robin Summeretto']],
  ['Ruan Mei', '阮·梅', ['阮梅']],
  ['Saber', 'Saber', ['阿尔托莉雅·潘德拉贡', 'Artoria Pendragon']],
  ['Sampo', '桑博'],
  ['Seele', '希儿'],
  ['Serval', '希露瓦'],
  ['Silver Wolf', '银狼'],
  ['Silver Wolf • Lv. 999', '银狼LV.999', ['Silver Wolf LV.999']],
  ['Sparkle', '花火'],
  ['Sparxie', '火花'],
  ['Sunday', '星期日'],
  ['Sushang', '素裳'],
  ['The Dahlia', '大丽花', ['康士坦丝', 'Constance']],
  ['The Herta', '大黑塔'],
  ['Tingyun', '停云'],
  ['Fugue', '忘归人', ['Tingyun • Fugue']],
  ['Topaz & Numby', '托帕&账账', ['托帕', 'Topaz', '账账', 'Numby']],
  ['Trailblazer', '开拓者'],
  ['Stelle', '星'],
  ['Caelus', '穹'],
  ['Tribbie', '缇宝'],
  ['Welt', '瓦尔特'],
  ['Xueyi', '雪衣'],
  ['Yanqing', '彦卿'],
  ['Yao Guang', '爻光'],
  ['Yukong', '驭空'],
  ['Yunli', '云璃'],
  ['Aventurine • Waveflair', '砂金·戏浪', ['Aventurine Waveflair']],
  ['Pearl', '真珠', ['珍珠']],
])

const zenlessZoneZero = characterTags('zzz', 'Zenless Zone Zero', [
  ['Alice', '爱丽丝', ['Alice Thymefield']],
  ['Anby Demara', '安比·德玛拉', ['安比', 'Anby']],
  ['Soldier 0 - Anby', '零号·安比', ['零号安比', 'Anby: Soldier 0']],
  ['Anton Ivanov', '安东·伊万诺夫', ['安东', 'Anton']],
  ['Aria', '爱芮'],
  ['Astra Yao', '耀嘉音'],
  ['Banyue', '般岳'],
  ['Ben Bigger', '本·比格', ['本', 'Ben']],
  ['Billy Kid', '比利·奇德', ['比利', 'Billy']],
  ['Starlight - Billy', '星徽·比利', ['Billy - Starlight']],
  ['Burnice White', '柏妮思·怀特', ['柏妮思', 'Burnice']],
  ['Caesar King', '凯撒·金', ['凯撒', 'Caesar']],
  ['Cissia', '希希芙'],
  ['Claret', '克拉蕾'],
  ['Corin Wickes', '可琳·威克斯', ['可琳', 'Corin']],
  ['Dialyn', '琉音'],
  ['Ellen Joe', '艾莲·乔', ['艾莲', 'Ellen']],
  ['Evelyn Chevalier', '伊芙琳·契瓦利尔', ['伊芙琳', 'Evelyn']],
  ['Grace Howard', '格莉丝·霍华德', ['格莉丝', 'Grace']],
  ['Asaba Harumasa', '浅羽悠真', ['悠真', 'Harumasa']],
  ['Hugo Vlad', '雨果·维拉德', ['雨果', 'Hugo']],
  ['Jane Doe', '简·杜', ['简', 'Jane']],
  ['Ju Fufu', '橘福福'],
  ['Koleda Belobog', '珂蕾妲·贝洛伯格', ['珂蕾妲', 'Koleda']],
  ['Lighter', '莱特'],
  ['Lucia', '卢西娅'],
  ['Luciana de Montefio', '露西', ['Lucy', '露西安娜·德·蒙特夫']],
  ['Von Lycaon', '冯·莱卡恩', ['莱卡恩', 'Lycaon']],
  ['Komano Manato', '狛野真斗', ['真斗', 'Manato']],
  ['Hoshimi Miyabi', '星见雅', ['雅', 'Miyabi']],
  ['Nangong Yu', '南宫羽'],
  ['Nekomiya Mana', '猫宫又奈', ['猫又', 'Nekomata']],
  ['Nicole Demara', '妮可·德玛拉', ['妮可', 'Nicole']],
  ['Norma', '诺姆'],
  ['Orphie & Magus', '奥菲丝&鬼火', ['Orphie Magnusson & Magus', '奥菲丝', '鬼火']],
  ['Pan Yinhu', '潘引壶'],
  ['Piper Wheel', '派派·韦尔', ['派派', 'Piper']],
  ['Promeia', '普罗米娅'],
  ['Pulchra', '波可娜'],
  ['Pyrois', '佩洛伊斯'],
  ['Qingyi', '青衣'],
  ['Remielle Dan', '蕾米埃尔·丹', ['蕾米埃尔', 'Remielle']],
  ['Alexandrina Sebastiane', '亚历山德丽娜·莎芭丝缇安', ['丽娜', 'Rina']],
  ['Seed', '席德'],
  ['Seth Lowell', '赛斯·洛威尔', ['赛斯', 'Seth']],
  ['Sigrid', '希格莉德'],
  ['Soldier 11', '11号'],
  ['Soukaku', '苍角'],
  ['Sunna', '千夏'],
  ['Trigger', '扳机'],
  ['Velina', '维琳娜'],
  ['Vivian Banshee', '薇薇安·班希', ['薇薇安', 'Vivian']],
  ['Tsukishiro Yanagi', '月城柳', ['柳', 'Yanagi']],
  ['Ye Shunguang', '叶瞬光'],
  ['Yidhari', '伊德海莉', ['Yidhari Murphy', '伊德海莉·墨菲']],
  ['Yixuan', '仪玄'],
  ['Ukinami Yuzuha', '浮波柚叶', ['柚叶', 'Yuzuha']],
  ['Zhao', '照'],
  ['Zhu Yuan', '朱鸢'],
  ['Roxy', '洛克茜'],
  ['Phoenix', '菲欧妮'],
  ['Severian', '赛维里安'],
  ['Sunbringer', '挽昼'],
  ['The Storyteller', '故事的讲述者'],
  ['Belle', '铃'],
  ['Wise', '哲'],
])

const wutheringWaves = characterTags('wuwa', 'Wuthering Waves', [
  ['Aalto', '秋水'],
  ['Aemeath', '爱弥斯'],
  ['Augusta', '奥古斯塔'],
  ['Baizhi', '白芷'],
  ['Brant', '布兰特'],
  ['Buling', '卜灵'],
  ['Calcharo', '卡卡罗'],
  ['Camellya', '椿'],
  ['Cantarella', '坎特蕾拉'],
  ['Carlotta', '珂莱塔'],
  ['Cartethyia', '卡提希娅'],
  ['Changli', '长离'],
  ['Chisa', '千咲'],
  ['Chixia', '炽霞'],
  ['Ciaccona', '夏空'],
  ['Danjin', '丹瑾'],
  ['Denia', '达妮娅'],
  ['Encore', '安可'],
  ['Galbrena', '嘉贝莉娜'],
  ['Hiyuki', '绯雪'],
  ['Iuno', '尤诺'],
  ['Jianxin', '鉴心'],
  ['Jingran', '景燃'],
  ['Jinhsi', '今汐'],
  ['Jiyan', '忌炎'],
  ['Lingyang', '凌阳'],
  ['Lucilla', '洛瑟菈'],
  ['Lucy', '露西'],
  ['Lumi', '灯灯'],
  ['Lupa', '露帕'],
  ['Luuk Herssen', '陆·赫斯', ['陆赫斯']],
  ['Lynae', '琳奈'],
  ['Mornye', '莫宁'],
  ['Mortefi', '莫特斐'],
  ['Phoebe', '菲比'],
  ['Phrolova', '弗洛洛'],
  ['Qingxiao', '清宵'],
  ['Qiuyuan', '仇远'],
  ['Rebecca', '丽贝卡'],
  ['Roccia', '洛可可'],
  ['Rover', '漂泊者'],
  ['Sanhua', '散华'],
  ['Sigrika', '西格莉卡'],
  ['Suisui', '穗穗'],
  ['Taoqi', '桃祈'],
  ['The Shorekeeper', '守岸人', ['Shorekeeper']],
  ['Verina', '维里奈'],
  ['Xiangli Yao', '相里要'],
  ['Yangyang', '秧秧'],
  ['Yangyang • Xuanling', '秧秧·玄翎', ['Yangyang: Xuanling', 'Yangyang Xuanling']],
  ['Yinlin', '吟霖'],
  ['Youhu', '釉瑚'],
  ['Yuanwu', '渊武'],
  ['Zani', '赞妮'],
  ['Zhezhi', '折枝'],
  ['Hsin', '心', ['心月狐']],
  ['Suoming', '锁暝'],
])

export const ipSections: readonly PromptTagSection[] = [
  { id: 'ip-genshin', labelZh: '原神', labelEn: 'Genshin Impact', parentId: 'ip-genshin', parentZh: '原神', parentEn: 'Genshin Impact', tags: genshinImpact },
  { id: 'ip-star-rail', labelZh: '崩坏：星穹铁道', labelEn: 'Honkai: Star Rail', parentId: 'ip-star-rail', parentZh: '崩坏：星穹铁道', parentEn: 'Honkai: Star Rail', tags: honkaiStarRail },
  { id: 'ip-zzz', labelZh: '绝区零', labelEn: 'Zenless Zone Zero', parentId: 'ip-zzz', parentZh: '绝区零', parentEn: 'Zenless Zone Zero', tags: zenlessZoneZero },
  { id: 'ip-wuwa', labelZh: '鸣潮', labelEn: 'Wuthering Waves', parentId: 'ip-wuwa', parentZh: '鸣潮', parentEn: 'Wuthering Waves', tags: wutheringWaves },
]
